### ISSUE TITLE
Random current temperature readouts

### ISSUE THREAD

**Issue by compo30** [omerfaruk-aran/esphome_samsung_hvac_bus#110]
Hi,
First of all thanks for the work on this it’s been great to play around with! It’s mostly working great but am having one weird issue where the ‘current temperature’ readout shows random values at times. The other day it was showing 58 degrees Celsius and then dropped to 3 degrees. Any ideas what could be causing this?

**Comment by lanwin** [comment]
Hi @compo30, we need more information's to do something about hat.

First question is if you use NASA or NonNASA. Then we need logs from the corresponding timeframes. These logs need to contain the raw messages. Please turn on `debug_log_messages` and `debug_log_messages_raw` you can find more about that here https://github.com/lanwin/esphome_samsung_ac?tab=readme-ov-file#development
