### ISSUE TITLE
[COMMON] The program size (2038817 bytes) is greater than maximum allowed (1835008 bytes)

### ISSUE THREAD

**Issue by bzumik1** [omerfaruk-aran/esphome_samsung_hvac_bus#149]
Hi everyone,

I am encountering an error when adding `esp32_improv` to my configuration. Please see the attached screenshot for details:

<img width="982" alt="image" src="https://github.com/user-attachments/assets/d7ef664b-177a-4269-80ea-58d2fbdec900">

I wanted to raise a point regarding the increasing size of the samsung_as files. If it is not feasible to reduce their size, I understand. However, as we continue to add new features, not all of which are necessary for every scenario, the program size could potentially become an issue even without additional components.

Thank you for your attention to this matter.

**Comment by brazoayeye** [comment]
It's a known problem, discussed also in https://github.com/lanwin/esphome_samsung_ac/discussions/140
