### ISSUE TITLE
[Non-NASA] Test Beep - Not Important (AJ050NCJ2EG)

### ISSUE THREAD

**Issue by TCB13** [omerfaruk-aran/esphome_samsung_hvac_bus#77]
I've noticed that my remote has the ability to "beep" the unit for testing:

![image](https://github.com/lanwin/esphome_samsung_ac/assets/6315832/b6139fc5-8c94-4748-8c3c-f8fcfa0a775c)

This isn't an important feature but could be an interesting way to have a test button on ESPHome to quickly identify indoor units. Attaches you may find the log produced by unit `01` while making the beep.

[BEEP.txt](https://github.com/lanwin/esphome_samsung_ac/files/14179140/BEEP.txt)

**Comment by lanwin** [comment]
@matthias882 did you have an idea how to find witch message triggers the beep?

**Comment by TCB13** [comment]
> ist there something else on the bus than 2 indoor and 1 outdoor units?

No. I assume `CC` is the outdoor unit, but I might be wrong.

**Comment by matthias882** [comment]
the outdoor-unit should be the c8
in my system (2xIU and 1xOU) only the c8 talks to the inoor units

**Comment by TCB13** [comment]
> there is a fourth device on the bus

I only have the outdoor unit and two indoor units. What about the ESP itself? How does it speak?

**Comment by matthias882** [comment]
the esp currently talks as D0 and nobody asked him before ;) D0 should normaly be the SNet PCSoftware.

I think there is some other device in the outdoor unit, c8 is the mainboard and cc some additional thing connected to the mainboard by the bus.

But back to he topic. There is the possibility hat the beep commands don't go over the bus. The infrared-remote says to he indoor-unit that it has to beep. There is no need for the IU to tell it to someone else. Its a thing only between the remote and the IU I think.
